language: groovy
jdk:
- oraclejdk8
script:
- ./gradlew runScript

before_script: 
- git config --global user.email "travis@yml.se"
- git config --global user.name "Travis"
- git remote -v

after_script:
- git add .
- git commit -m "updating outputs" 
- git push origin gh-pages

# whitelist
branches:
  only:
    - master
    - gh-pages