language: groovy
jdk:
- oraclejdk8
script:
- ./gradlew runScript

before_install:
- openssl aes-256-cbc -K $encrypted_9112fb2807d4_key -iv $encrypted_9112fb2807d4_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key

before_script: 
- git config --global user.email "travis@yml.se"
- git config --global user.name "Travis"
- git remote add github git@github.com:emtipz/2016.git

after_script:
- git status
- git add .
- git commit -m "updating outputs"
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- git push github gh-pages

# whitelist
branches:
  only:
    - master
    - gh-pages
